### ISSUE TITLE
Testcontainers support for MongoDB Atlas is broken

### ISSUE THREAD

**Issue by ThomasVitale** [spring-projects/spring-ai#4711]
**Bug description**

Support for the `MongoDbAtlasLocalContainer` as a development/test container relying on Spring Boot's `ConnectionDetails` seems to be broken. The culprit seems to be the SSL support in `MongoConnectionDetails`.

The result is the application fails starting up.

**Environment**

Spring AI: 1.1.0-SNAPSHOT
Spring Boot: 3.5.7

**Expected behavior**

I expect the application succeeds starting up when using [Spring AI Testcontainers](https://docs.spring.io/spring-ai/reference/1.1-SNAPSHOT/api/testcontainers.html).

**Minimal Complete Reproducible example**

Check the [demo](https://github.com/ThomasVitale/spring-ai-mongodb-atlas-error-reproducer#) reproducing the error and providing more details about what's happening.

**Comment by quaff** [comment]
It seems duplicate of https://github.com/spring-projects/spring-ai/pull/4175

**Comment by sobychacko** [comment]
Closing this issue, since it has been fixed by the other PR mentioned above.

**Comment by ThomasVitale** [comment]
@sobychacko the linked PR was never merged. I tested this against the latest snapshot of Spring AI and the problem is still there.
